[[CURL]]
arch = "aarch64"
git-tree-sha1 = "df2c6540bbb68a2554c7f253a6798947697f8611"
os = "macos"

    [[CURL.download]]
    sha256 = "21ee6295ccf7599574f4b6bbe0a1e2ece78ca9210b2c7cad8612fcc174a60260"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.6.0+0/CURL.v8.6.0.aarch64-apple-darwin.tar.gz"
[[CURL]]
arch = "aarch64"
git-tree-sha1 = "1d2f1986b5fa48b82bd5fe5653288fa92e9df10f"
libc = "glibc"
os = "linux"

    [[CURL.download]]
    sha256 = "a9627355a54f74bec6186fbe033253d8e599eeb55378755bf021c1fd8697c5ad"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.6.0+0/CURL.v8.6.0.aarch64-linux-gnu.tar.gz"
[[CURL]]
arch = "aarch64"
git-tree-sha1 = "3f1fb7de4922acf7a3672dbf9083ed4e85b5ac59"
libc = "musl"
os = "linux"

    [[CURL.download]]
    sha256 = "e9d60981dc02755e1b3c5d9aa88c588091b982c679abc166fb72f121caf0fa4c"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.6.0+0/CURL.v8.6.0.aarch64-linux-musl.tar.gz"
[[CURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e0cc52bc644848f86159501cc6cc2dfe7a8d4a05"
libc = "glibc"
os = "linux"

    [[CURL.download]]
    sha256 = "9a699c42adb775af5e73ae2b8de3a0e6afa85aa6f4a3d98d065d9e4c5992d917"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.6.0+0/CURL.v8.6.0.armv6l-linux-gnueabihf.tar.gz"
[[CURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1bc263d7f9f494dc2b174e3f9aa1e47c2a0d2ad5"
libc = "musl"
os = "linux"

    [[CURL.download]]
    sha256 = "80eeb4e70c02697ad35dacf8342214584f3ddadcc69d7f3d17953582e2a1b97f"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.6.0+0/CURL.v8.6.0.armv6l-linux-musleabihf.tar.gz"
[[CURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "21c12d63c546e6ccefba43bb5e4520cae9dcd5cc"
libc = "glibc"
os = "linux"

    [[CURL.download]]
    sha256 = "0990d89ae282373d4123b7932fb5875d0a99f221042df132d2a6b3b9c1a0570e"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.6.0+0/CURL.v8.6.0.armv7l-linux-gnueabihf.tar.gz"
[[CURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "464c8e4a0f5a55149617271d5017947ac1e6028e"
libc = "musl"
os = "linux"

    [[CURL.download]]
    sha256 = "764db6b7c4820b74881108329e773a4eaf36e3449766f5abe9ea360fac93cd98"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.6.0+0/CURL.v8.6.0.armv7l-linux-musleabihf.tar.gz"
[[CURL]]
arch = "i686"
git-tree-sha1 = "aa062b77089621a43d8c492a4f12ac3d23e14fb0"
libc = "glibc"
os = "linux"

    [[CURL.download]]
    sha256 = "0c3489ff24ab967f8160dffbf283628215edf871c5d1264c7cdf3afa82e91db9"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.6.0+0/CURL.v8.6.0.i686-linux-gnu.tar.gz"
[[CURL]]
arch = "i686"
git-tree-sha1 = "a119ac3fa88ed5cbd05ab8a801601c2dbf656f08"
libc = "musl"
os = "linux"

    [[CURL.download]]
    sha256 = "2546dd6ce28cc9250b90bc2c110f416823e21701e35e77dd2f57bf4d8df93e89"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.6.0+0/CURL.v8.6.0.i686-linux-musl.tar.gz"
[[CURL]]
arch = "i686"
git-tree-sha1 = "61cf7c20773616d3c74be4cfef312268d0f5fc02"
os = "windows"

    [[CURL.download]]
    sha256 = "523e7acdc2902853acc0f75907f8e496f749bd0d69e03755fc1bb82d56707346"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.6.0+0/CURL.v8.6.0.i686-w64-mingw32.tar.gz"
[[CURL]]
arch = "powerpc64le"
git-tree-sha1 = "5cc6bdb95889095d5ab32d7ecebf6206ea26a60f"
libc = "glibc"
os = "linux"

    [[CURL.download]]
    sha256 = "085be5f899789ed5cdf2ecab4598c8c95debc9a9fe988aa0ecbbe822d63d511a"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.6.0+0/CURL.v8.6.0.powerpc64le-linux-gnu.tar.gz"
[[CURL]]
arch = "x86_64"
git-tree-sha1 = "33b7fcc2b9c028622bb7083c2c72eb676396537b"
os = "macos"

    [[CURL.download]]
    sha256 = "cfe1c4808d532b576c7f56a466df6694fe7560efbc0312bbbdcd9f319ab1b318"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.6.0+0/CURL.v8.6.0.x86_64-apple-darwin.tar.gz"
[[CURL]]
arch = "x86_64"
git-tree-sha1 = "3492feffa551dd7d944afd95ab1f323ed0f0f6c0"
libc = "glibc"
os = "linux"

    [[CURL.download]]
    sha256 = "19906ef9ceaa495ed7b40ec8cfeb132aea8d01e503e8b1ed4a4bc38d0623f6cf"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.6.0+0/CURL.v8.6.0.x86_64-linux-gnu.tar.gz"
[[CURL]]
arch = "x86_64"
git-tree-sha1 = "8c28695d1e241cfab7474802a46a68fdc0c0309a"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[CURL.download]]
    sha256 = "da9a0709a87cbf6f05112ad3f6dd0789835537b462a2e06f06107f6a54c9ae73"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.6.0+0/CURL.v8.6.0.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[CURL]]
arch = "x86_64"
git-tree-sha1 = "eb9689a376a5474352713c615ef8dc7f9ce0cd06"
libc = "musl"
os = "linux"

    [[CURL.download]]
    sha256 = "bb8f801b2cff7367cdb622ac872fdfd532154876473d2398a52e9919b7917174"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.6.0+0/CURL.v8.6.0.x86_64-linux-musl.tar.gz"
[[CURL]]
arch = "x86_64"
git-tree-sha1 = "fee3edd545f77cae5805daa1e86f8878a7492573"
os = "freebsd"

    [[CURL.download]]
    sha256 = "23b95dd426ca6f8883ae6932909e962bfcc0b3790bf7aeb29b141579c3c6b686"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.6.0+0/CURL.v8.6.0.x86_64-unknown-freebsd.tar.gz"
[[CURL]]
arch = "x86_64"
git-tree-sha1 = "63347329390443e253ec334be4fbb4098d79efcb"
os = "windows"

    [[CURL.download]]
    sha256 = "e9a15811dadbcca389d7c21d2aed07ee72a5ac3acea208deae7dadf90f7fcb94"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.6.0+0/CURL.v8.6.0.x86_64-w64-mingw32.tar.gz"
