[[CURL]]
arch = "aarch64"
git-tree-sha1 = "5c3b724b370c46e06ee251bd8f6285ef19236e00"
os = "macos"

    [[CURL.download]]
    sha256 = "a9c73e8293aaf2728c586a115e1b9deeb927733c20c90781ce44e4b0118abba9"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.5.0+0/CURL.v8.5.0.aarch64-apple-darwin.tar.gz"
[[CURL]]
arch = "aarch64"
git-tree-sha1 = "972cced712d4110b0a6147d192809c05c347dc2a"
libc = "glibc"
os = "linux"

    [[CURL.download]]
    sha256 = "655ccd5aa63fd50436353bf080ba466d9ed08f46fb51bdb261f35a04a6d61b04"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.5.0+0/CURL.v8.5.0.aarch64-linux-gnu.tar.gz"
[[CURL]]
arch = "aarch64"
git-tree-sha1 = "59c926fa22d7b2abeab4ebdce8fa00b1c7653d35"
libc = "musl"
os = "linux"

    [[CURL.download]]
    sha256 = "9c043b57bd1b35dc0e1155129da363204a16515f07a82dc0ad30aceda02f66f1"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.5.0+0/CURL.v8.5.0.aarch64-linux-musl.tar.gz"
[[CURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6b79947379418c8bb7498f121258d9b92e36c6af"
libc = "glibc"
os = "linux"

    [[CURL.download]]
    sha256 = "821c0116a0119cc447ae9c657840541184b19bd9c149e8476e51c00ab2a2f6af"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.5.0+0/CURL.v8.5.0.armv6l-linux-gnueabihf.tar.gz"
[[CURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "029de6b45c47060ff53945c488b307777deaf6db"
libc = "musl"
os = "linux"

    [[CURL.download]]
    sha256 = "5eda880559eefc03b19344727cd76e353340951d5dbb288ca934fa4ae0c30639"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.5.0+0/CURL.v8.5.0.armv6l-linux-musleabihf.tar.gz"
[[CURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "940683ac1671fab01069e36a731ec3d3ddbdbefd"
libc = "glibc"
os = "linux"

    [[CURL.download]]
    sha256 = "1af1d669daa9e875f4988023b17d54b8cd121a3563c0d68b75e4606e13e30e9f"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.5.0+0/CURL.v8.5.0.armv7l-linux-gnueabihf.tar.gz"
[[CURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8d75d93cb53f2be60424c8d05fd27434ad29dab5"
libc = "musl"
os = "linux"

    [[CURL.download]]
    sha256 = "6f0e65cd1adf8441079f7651e5801fcfcc84aa789dfa290621a224a1b7aafc76"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.5.0+0/CURL.v8.5.0.armv7l-linux-musleabihf.tar.gz"
[[CURL]]
arch = "i686"
git-tree-sha1 = "bae1c72fece11a1d5b16e915da1bf4387bf9ca42"
libc = "glibc"
os = "linux"

    [[CURL.download]]
    sha256 = "3c0f3d63b6fa3f38dd06b5906da7749e214abe7ada9a4a4ac8d2d3f1d368725d"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.5.0+0/CURL.v8.5.0.i686-linux-gnu.tar.gz"
[[CURL]]
arch = "i686"
git-tree-sha1 = "295a2d8e2b808dba817c0966dd34380b54114725"
libc = "musl"
os = "linux"

    [[CURL.download]]
    sha256 = "e36192d8661032646053c8845eeee9cc31e683d4d7996294bd8b003d8b1f8720"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.5.0+0/CURL.v8.5.0.i686-linux-musl.tar.gz"
[[CURL]]
arch = "i686"
git-tree-sha1 = "4305ab73ff8e3c6ce4036b24f6a5a01975af4077"
os = "windows"

    [[CURL.download]]
    sha256 = "4af681c8c1cb0d9ca535abf8da264c01b88e50c5af984da60a89d94c120c3588"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.5.0+0/CURL.v8.5.0.i686-w64-mingw32.tar.gz"
[[CURL]]
arch = "powerpc64le"
git-tree-sha1 = "f50db290faa6fc17ff534072248748d54c1b97d6"
libc = "glibc"
os = "linux"

    [[CURL.download]]
    sha256 = "99156ba679569cbbc8dca4f27bc7c763ece0fe4d57e3252d3134e6fbe4730a75"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.5.0+0/CURL.v8.5.0.powerpc64le-linux-gnu.tar.gz"
[[CURL]]
arch = "x86_64"
git-tree-sha1 = "dd942280a2518bb3e85df904cf101f092d1bd72c"
os = "macos"

    [[CURL.download]]
    sha256 = "745802255a2b60087681743856aacae8d1a07a0afdb7288802184a946881fc6e"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.5.0+0/CURL.v8.5.0.x86_64-apple-darwin.tar.gz"
[[CURL]]
arch = "x86_64"
git-tree-sha1 = "091d1cd2fc49252d0359782c9faa1e1188f610d8"
libc = "glibc"
os = "linux"

    [[CURL.download]]
    sha256 = "deafd22b29ee625fe5ceaaa33aadf443fd4351a09a6bd73962472006eeb46541"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.5.0+0/CURL.v8.5.0.x86_64-linux-gnu.tar.gz"
[[CURL]]
arch = "x86_64"
git-tree-sha1 = "075ca33f71613b151744f602c4844f1448920306"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[CURL.download]]
    sha256 = "0a5d0cca6036de1266a99cc2c73e99ca43eebc8670040c82044bd0c4c21628dd"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.5.0+0/CURL.v8.5.0.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[CURL]]
arch = "x86_64"
git-tree-sha1 = "1364fc41c39153671a8981a206a174f02b8acb9a"
libc = "musl"
os = "linux"

    [[CURL.download]]
    sha256 = "c632505ff4aab09c4d1c6137a4e9720398df65c70fc25d57614ca96e58f36d59"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.5.0+0/CURL.v8.5.0.x86_64-linux-musl.tar.gz"
[[CURL]]
arch = "x86_64"
git-tree-sha1 = "9f5dbe2b5224ac7c804ea91e1e182c7398942639"
os = "freebsd"

    [[CURL.download]]
    sha256 = "562a668539c70bcafe3d8f5e37abbf51bf1faab5a0867a94e9e4f32e79d5d30c"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.5.0+0/CURL.v8.5.0.x86_64-unknown-freebsd.tar.gz"
[[CURL]]
arch = "x86_64"
git-tree-sha1 = "ffe498f3c68d2fddc868c7ba01f8cb5d1f947cd7"
os = "windows"

    [[CURL.download]]
    sha256 = "a948a6152e08951670d807a6343b75c8f918d9e8b01863b7c52489ac8a3f39e5"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.5.0+0/CURL.v8.5.0.x86_64-w64-mingw32.tar.gz"
