[[CURL]]
arch = "aarch64"
git-tree-sha1 = "91b63a92f2b93ef095a720ec20b605b97caf3f1b"
os = "macos"

    [[CURL.download]]
    sha256 = "3b234d9daa9bdd18ad33dcbc5f6778cdad1860ce2c774f79426b3699437b1aad"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.9.0+0/CURL.v8.9.0.aarch64-apple-darwin.tar.gz"
[[CURL]]
arch = "aarch64"
git-tree-sha1 = "3398d5416f282c63ec1c606780a9358fc80d8c18"
libc = "glibc"
os = "linux"

    [[CURL.download]]
    sha256 = "a6c41868fb4eb74679e437a64b25bb2c619cb0a29f2fcde9ef43daae0e2ac021"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.9.0+0/CURL.v8.9.0.aarch64-linux-gnu.tar.gz"
[[CURL]]
arch = "aarch64"
git-tree-sha1 = "2383661c369942e3840bd4cc6e68c537bd01dffd"
libc = "musl"
os = "linux"

    [[CURL.download]]
    sha256 = "30a0d9c195dab31f69cbc4795211b9ca571948a47b09b29aefb8ce4f381fffbb"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.9.0+0/CURL.v8.9.0.aarch64-linux-musl.tar.gz"
[[CURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9dc87dd5e6c5a844e6153d11602c04bd2df3ccc5"
libc = "glibc"
os = "linux"

    [[CURL.download]]
    sha256 = "025d28c82a9f5ce8cc13605c393f28c443c60a55425241e56a9051fdb07261f4"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.9.0+0/CURL.v8.9.0.armv6l-linux-gnueabihf.tar.gz"
[[CURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d0fff9dd4c3770c361579bd68d2f22d2236ef2ec"
libc = "musl"
os = "linux"

    [[CURL.download]]
    sha256 = "1002cc462ab821072bcfc1410178a8cab777a80433634053f289533942f19625"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.9.0+0/CURL.v8.9.0.armv6l-linux-musleabihf.tar.gz"
[[CURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "44180ed83081324195e8dde0dad67c97930c4fbc"
libc = "glibc"
os = "linux"

    [[CURL.download]]
    sha256 = "c7e4329facd24bbc5ccd7185f691a670515a8e77d8b3a110ec723cf9d56537d3"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.9.0+0/CURL.v8.9.0.armv7l-linux-gnueabihf.tar.gz"
[[CURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e907f380240a4e6cb209fa222134f979dffe3be1"
libc = "musl"
os = "linux"

    [[CURL.download]]
    sha256 = "be70400baab29c1f3885cbebc8ffd98ece9dacee0df55c76f56d932f592cc28b"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.9.0+0/CURL.v8.9.0.armv7l-linux-musleabihf.tar.gz"
[[CURL]]
arch = "i686"
git-tree-sha1 = "93c00e0c4e5bdcbf2953bda5e5b155b37fc52010"
libc = "glibc"
os = "linux"

    [[CURL.download]]
    sha256 = "6dde09e15d3765ab8ce5317833674d81878cfb4f7c2bb74d7de114eebae432e6"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.9.0+0/CURL.v8.9.0.i686-linux-gnu.tar.gz"
[[CURL]]
arch = "i686"
git-tree-sha1 = "fce9709ebe97ed938253718e8be3b3f943fae8b9"
libc = "musl"
os = "linux"

    [[CURL.download]]
    sha256 = "776b0ebc5a76b0bc7665b2e0d152496b934608dc4d83c60eb716fee937f56409"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.9.0+0/CURL.v8.9.0.i686-linux-musl.tar.gz"
[[CURL]]
arch = "i686"
git-tree-sha1 = "354c601348ef8cc5fcb14f20e73891207434cd7c"
os = "windows"

    [[CURL.download]]
    sha256 = "2b970a544befe01e360c1284a0f2641f642e15e94ed60975a88b28a44254a44f"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.9.0+0/CURL.v8.9.0.i686-w64-mingw32.tar.gz"
[[CURL]]
arch = "powerpc64le"
git-tree-sha1 = "d89049297b0d744fcf08d2d77d4f193b6314159b"
libc = "glibc"
os = "linux"

    [[CURL.download]]
    sha256 = "bdfd7c5cb477396c81da5512b80f056ecd6b4523b4213d6895b85137cf343899"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.9.0+0/CURL.v8.9.0.powerpc64le-linux-gnu.tar.gz"
[[CURL]]
arch = "x86_64"
git-tree-sha1 = "8f534c5c65d401bf70be0ad2de9cdca575cde589"
os = "macos"

    [[CURL.download]]
    sha256 = "28bce945f914cd6eae603fdd7f9a661be5211338f9412c15c9c4cbbba004e9c4"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.9.0+0/CURL.v8.9.0.x86_64-apple-darwin.tar.gz"
[[CURL]]
arch = "x86_64"
git-tree-sha1 = "fb5a22266d2acf76ed8017363eb4ed0aefe87b7a"
libc = "glibc"
os = "linux"

    [[CURL.download]]
    sha256 = "8deb32e87b0ed18059522ca441a9242630d4863d24799f2913c8e7241752b593"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.9.0+0/CURL.v8.9.0.x86_64-linux-gnu.tar.gz"
[[CURL]]
arch = "x86_64"
git-tree-sha1 = "923653e03af1343e7fa086a0339b2eecc0bdc826"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[CURL.download]]
    sha256 = "ef8dabce59d31bd76e9c0a5cdee508e659f496c64aee3f21c30894cb1769b684"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.9.0+0/CURL.v8.9.0.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[CURL]]
arch = "x86_64"
git-tree-sha1 = "4893f1dceeb7e715e29d2d8a8ebe1cf6d5177909"
libc = "musl"
os = "linux"

    [[CURL.download]]
    sha256 = "53bd6811ac0dccea96df38a1614ece61d411ee3617e59c149f3a20534cb6346e"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.9.0+0/CURL.v8.9.0.x86_64-linux-musl.tar.gz"
[[CURL]]
arch = "x86_64"
git-tree-sha1 = "b4ea78a44c9ab9266fcd0f8a9e5809b6c678bd61"
os = "freebsd"

    [[CURL.download]]
    sha256 = "bd82d18384430f888b9294f4f0b58733a97c5f6bb0d0a2f204299ad9e85ece25"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.9.0+0/CURL.v8.9.0.x86_64-unknown-freebsd.tar.gz"
[[CURL]]
arch = "x86_64"
git-tree-sha1 = "b5b5e5e0cf729e3ba1297bdb487d8a56ee1e394a"
os = "windows"

    [[CURL.download]]
    sha256 = "d60f7a1bc7a113c4a36413150fb33b2fb0b1096a5b8ffbaa0cafbefadd2fb9c1"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.9.0+0/CURL.v8.9.0.x86_64-w64-mingw32.tar.gz"
