[[CURL]]
arch = "aarch64"
git-tree-sha1 = "08c94c43059ad7a8aceab50687f99e9f54a60163"
os = "macos"

    [[CURL.download]]
    sha256 = "4c4f2d293d4ea17bded7726a147fe1ebb8f85a1c55f38644de4ccc306607c269"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.17.0+0/CURL.v8.17.0.aarch64-apple-darwin.tar.gz"
[[CURL]]
arch = "aarch64"
git-tree-sha1 = "52dd1814159e09690cafc3c1200e63bd99ced6b6"
libc = "glibc"
os = "linux"

    [[CURL.download]]
    sha256 = "18e93050bb45d3db2f630c02803fc9f3319a539382a382966ee46e3c55fe4f3e"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.17.0+0/CURL.v8.17.0.aarch64-linux-gnu.tar.gz"
[[CURL]]
arch = "aarch64"
git-tree-sha1 = "a8a8ef6aa830dd6f746087a3774ea2d893426e78"
libc = "musl"
os = "linux"

    [[CURL.download]]
    sha256 = "a847552f03d615ca0f5e852be1fde4a7f192cbaa51ffd71d7737be994d6c23a8"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.17.0+0/CURL.v8.17.0.aarch64-linux-musl.tar.gz"
[[CURL]]
arch = "aarch64"
git-tree-sha1 = "71fd7b05c0ed4af7f726a2af36a13fed0a05e8dc"
os = "freebsd"

    [[CURL.download]]
    sha256 = "b6de1e428a9a76bcaf85c16f9350ec5699e5579233ae36580513245936c7ffc5"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.17.0+0/CURL.v8.17.0.aarch64-unknown-freebsd.tar.gz"
[[CURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f0e092aa67a69e3476ae65a9612a2241bf032632"
libc = "glibc"
os = "linux"

    [[CURL.download]]
    sha256 = "26626981cced9d93a37110cf2d1c42b8096c696e8dbcf2418109248c6eec9a5f"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.17.0+0/CURL.v8.17.0.armv6l-linux-gnueabihf.tar.gz"
[[CURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d02d61893b2caa1200ae411396e42f7b4fc2174e"
libc = "musl"
os = "linux"

    [[CURL.download]]
    sha256 = "3939386a9f317fe044c130c35616975adeb4abd3e2911150aafb803523f6d9f0"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.17.0+0/CURL.v8.17.0.armv6l-linux-musleabihf.tar.gz"
[[CURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "98ace9ae911ea35a97ed3046aeb11b8053f51e49"
libc = "glibc"
os = "linux"

    [[CURL.download]]
    sha256 = "c5de0e4a1ba3a05399b5bce47cd816c62cab77a8ea0bf2208cac528c9c940d9c"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.17.0+0/CURL.v8.17.0.armv7l-linux-gnueabihf.tar.gz"
[[CURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e28c7ac5f9f25e7a6db60aa4e45809ab301dd0db"
libc = "musl"
os = "linux"

    [[CURL.download]]
    sha256 = "b64194719037d6bccca3509ce28393c33c3da65ca432512fa5aeaada45d09332"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.17.0+0/CURL.v8.17.0.armv7l-linux-musleabihf.tar.gz"
[[CURL]]
arch = "i686"
git-tree-sha1 = "2156f5600d9903997d8f6f789b1b4be3ad06f07c"
libc = "glibc"
os = "linux"

    [[CURL.download]]
    sha256 = "a457460e93e314eaf8e37084e5f72a8edd22dd00887073cd148f4e2737f07d0f"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.17.0+0/CURL.v8.17.0.i686-linux-gnu.tar.gz"
[[CURL]]
arch = "i686"
git-tree-sha1 = "51f7222c7d88192ab881310d19f126481fd63bba"
libc = "musl"
os = "linux"

    [[CURL.download]]
    sha256 = "9f431f289dc588f5cfd885bf170489002552e8082da434d9eb22777aa3184c3a"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.17.0+0/CURL.v8.17.0.i686-linux-musl.tar.gz"
[[CURL]]
arch = "i686"
git-tree-sha1 = "92be89e3526c83457288cd2090f5ec8d45886a10"
os = "windows"

    [[CURL.download]]
    sha256 = "2d55bc3011490bd266ee8a67f20317a267298cfea08c7437fe8dac17486e2393"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.17.0+0/CURL.v8.17.0.i686-w64-mingw32.tar.gz"
[[CURL]]
arch = "powerpc64le"
git-tree-sha1 = "29ddaa09b7dcc49a49810473e9c3be129c8dd3d4"
libc = "glibc"
os = "linux"

    [[CURL.download]]
    sha256 = "8e1c9bffba3741be16635a6502a86298f275611b60670b5de442b6f49985b2e5"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.17.0+0/CURL.v8.17.0.powerpc64le-linux-gnu.tar.gz"
[[CURL]]
arch = "riscv64"
git-tree-sha1 = "d67916a55b9d6ac00b723509c611e146074d689d"
libc = "glibc"
os = "linux"

    [[CURL.download]]
    sha256 = "ef4d0b39f521ba8974b5e6afa6d5ea596cfe5a772dd03948b3297aae4909a84d"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.17.0+0/CURL.v8.17.0.riscv64-linux-gnu.tar.gz"
[[CURL]]
arch = "x86_64"
git-tree-sha1 = "9e344701e3176bd8288ff9a52514c0934076a3df"
os = "macos"

    [[CURL.download]]
    sha256 = "bb1c27b87654725a7afed58d95e4dad94cdfc9d5344c8ee6d4221dc58c6b76d4"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.17.0+0/CURL.v8.17.0.x86_64-apple-darwin.tar.gz"
[[CURL]]
arch = "x86_64"
git-tree-sha1 = "764f1e9e0611b65bbdcb80ccda90226f21072fd2"
libc = "glibc"
os = "linux"

    [[CURL.download]]
    sha256 = "ccdc56f28ee5127d7ec28eb19e1485471aee018cec06330cb94c3ba46d669fdb"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.17.0+0/CURL.v8.17.0.x86_64-linux-gnu.tar.gz"
[[CURL]]
arch = "x86_64"
git-tree-sha1 = "cdfe70e10994899ea9961f3b5a08cc8ec5304cf0"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[CURL.download]]
    sha256 = "f567ab99a071ad8024b4a1c235cf784c21e7f0ff88262675f8fce1c752076827"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.17.0+0/CURL.v8.17.0.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[CURL]]
arch = "x86_64"
git-tree-sha1 = "4414bb1f62e91bbd9f605ac3f6a84cd7151ae01f"
libc = "musl"
os = "linux"

    [[CURL.download]]
    sha256 = "b4d546826958d43f7c96463dba6e3fd70e2c1cc357fac1ab69aca5e69974854e"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.17.0+0/CURL.v8.17.0.x86_64-linux-musl.tar.gz"
[[CURL]]
arch = "x86_64"
git-tree-sha1 = "b7788b647819088cd3a697cc38b36ccf2d9a30be"
os = "freebsd"

    [[CURL.download]]
    sha256 = "59d89d04c25960694a9ff7c9630a00375e4de00419501b5f0106c82176e87bb5"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.17.0+0/CURL.v8.17.0.x86_64-unknown-freebsd.tar.gz"
[[CURL]]
arch = "x86_64"
git-tree-sha1 = "bcf864d2b7c75a2ef33655487bbdfe4ad30bc9e5"
os = "windows"

    [[CURL.download]]
    sha256 = "1b22d3601ddbe7bbf9dc613aa5e4cb9efbaf70821a9b5a482d93cb46903b9c03"
    url = "https://github.com/JuliaBinaryWrappers/CURL_jll.jl/releases/download/CURL-v8.17.0+0/CURL.v8.17.0.x86_64-w64-mingw32.tar.gz"
